version: 2

models:
  - name: order_analysis
    description: "Model for analyzing order data"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
